name: Create a zip for Magisk

on:
  workflow_dispatch:
    inputs:      
      model:
        description: 'Your Model Number'
        required: true             
      model_name:
        description: 'Your model name in lowercase'
        required: true     
      imei:
        description: 'Your IMEI'
        required: true          
      version:
        description: 'Your Version or .*'
        required: true              

jobs:
  samloader-actions:
    runs-on: ubuntu-latest
    permissions:
      contents: write    

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install packages & setup
        run: |
          sudo apt update -y > /dev/null 2>&1
          sudo apt install python3 python-is-python3 awscli -y > /dev/null 2>&1 
          
      - name: Set environment variables
        run: |
          echo "MODEL=${{ github.event.inputs.model }}" >> $GITHUB_ENV
          echo "IMEI=${{ github.event.inputs.imei }}" >> $GITHUB_ENV
          echo "MY_VER=${{ github.event.inputs.version }}" >> $GITHUB_ENV  
          echo "MODEL_NAME=${{ github.event.inputs.model_name }}" >> $GITHUB_ENV          
          
      - name: Running samloader-actions
        run: |
          bash sam.sh      

      - name: Uploading Stock Files
        uses: actions/upload-artifact@v4
        with:
          name: "Stock files - ${{ env.MODEL }}"
          path: Dist/${{ github.event.inputs.model }}*.tar     

      - name: Upload to DigitalOcean Spaces
        run: |
          aws configure set aws_access_key_id ${{ secrets.DO_SPACES_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.DO_SPACES_SECRET }}
          aws configure set default.region ams3
          aws s3 cp Dist/${{ github.event.inputs.model_name }}*.tar ${{ secrets.DO_BUCKET_PATH }} --endpoint-url https://ams3.digitaloceanspaces.com
        env:
          DO_SPACES_KEY: ${{ secrets.DO_SPACES_KEY }}
          DO_SPACES_SECRET: ${{ secrets.DO_SPACES_SECRET }}
